StatCategory=   {
                'points':'PTS',
                'minutes':'MIN',
                'offensive_rebounds':'OREB',
                'defensive_rebounds':'DREB',
                'rebounds':'REB',
                'assists':'AST',
                'steals':'STL',
                'blocks':'BLK',
                'turnovers':'TOV',
                'efficiency':'EFF',
                'minutes':'MIN',
                'field goals made':'FGM',
                'field goals attempted':'FGA',
                'field goal percentage':'FG_PCT',
                'free throws made':'FTM',
                'free throws attempts':'FTA',
                'free throws percentage':'FT_PCT',
                'three point made':'FG3M',
                'three point attempts':'FG3A',
                'assist to turnover':'AST_TOV',
                'steals to turnover':'STL_TOV'
                 }